name:
  helxetL2Check

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: run install
        run: make install
      - name: get permission
        run: sudo chmod 777 bin/gendiff
      - name: run linter
        run: make lint
      - name: run tests 
        run: make gendiffTest
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_ID }}
        with:
          coverageCommand: make coverage
          coverageLocations: |
            ${{github.workspace}}/clover.xml:clover
          